// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWN1Fwdkz3oo4KXqkauqBk75ZbqnQmVQk',
    appId: '1:424988674969:web:28c11cad1c6cb38ec2e108',
    messagingSenderId: '424988674969',
    projectId: 'dopamine-60dfc',
    authDomain: 'dopamine-60dfc.firebaseapp.com',
    storageBucket: 'dopamine-60dfc.appspot.com',
    measurementId: 'G-54DCYEE4JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNDZguIPVpgkkDPZKLjgwy3D788sJCiyw',
    appId: '1:424988674969:android:67fcfd7b9735c87dc2e108',
    messagingSenderId: '424988674969',
    projectId: 'dopamine-60dfc',
    storageBucket: 'dopamine-60dfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3mURaxsup__9Gw2UIpqTkXJC7ABmlnlY',
    appId: '1:424988674969:ios:c3f4e84ee016fac2c2e108',
    messagingSenderId: '424988674969',
    projectId: 'dopamine-60dfc',
    storageBucket: 'dopamine-60dfc.appspot.com',
    iosBundleId: 'com.example.tStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWN1Fwdkz3oo4KXqkauqBk75ZbqnQmVQk',
    appId: '1:424988674969:web:1cc6a8d798d301eec2e108',
    messagingSenderId: '424988674969',
    projectId: 'dopamine-60dfc',
    authDomain: 'dopamine-60dfc.firebaseapp.com',
    storageBucket: 'dopamine-60dfc.appspot.com',
    measurementId: 'G-XVCM66SLCT',
  );
}
